FROM jboss/base-jdk:11

COPY wildfly-23.0.1.Final.tar.gz .

RUN tar -xzvf wildfly-23.0.1.Final.tar.gz

ENV JBOSS_HOME /opt/jboss/wildfly-23.0.1.Final

ENV LAUNCH_JBOSS_IN_BACKGROUND true

USER jboss

EXPOSE 8080

EXPOSE 9990

EXPOSE 9999

RUN  /opt/jboss/wildfly-23.0.1.Final/bin/add-user.sh admin Admin#93229 --silent 

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b" , "0.0.0.0" , "-bmanagement" , "0.0.0.0" ]